In [20]:
import json
import pandas as pd

def load_config(file_path):
    """Load configuration from a JSON file."""
    with open(file_path, 'r') as file:
        config = json.load(file)
    return config

knockout_results = load_config('/home/ron/Documents/Github/cross-modal-information-flow-in-MLLM/output/knockout_sae/knockout_run2_fixed_20260203_173906/knockout/knockout_results.json')
knockout_summary = load_config('/home/ron/Documents/Github/cross-modal-information-flow-in-MLLM/output/knockout_sae/knockout_run2_fixed_20260203_173906/knockout/knockout_summary.json')

df_results = pd.DataFrame(knockout_results)
df_summary = pd.DataFrame(knockout_summary)

In [21]:
df_results.describe()

,layer,base_true_logprob,base_false_logprob,base_margin,new_true_logprob,new_false_logprob,new_margin,margin_drop
count,51840.000000,51840.000000,51840.000000,51840.000000,51840.000000,51840.000000,51840.000000,51840.000000
mean,15.500000,-9.509619,-11.249766,1.740147,-9.475286,-11.198757,1.723472,0.016675
std,9.233182,1.780173,1.891623,1.487135,1.803880,1.923910,1.484021,0.123388
min,0.000000,-12.793176,-17.400183,0.003080,-13.141831,-18.112872,-0.773438,-1.021485
25%,7.750000,-10.581721,-12.303386,0.648438,-10.577315,-12.281143,0.636719,-0.005164
50%,15.500000,-10.055287,-11.387151,1.278488,-10.048003,-11.343644,1.270833,0.000000
75%,23.250000,-9.184890,-10.430600,2.440366,-9.090929,-10.386140,2.425781,0.011719
max,31.000000,-3.482040,-3.808373,8.106689,-2.753299,-3.511609,8.408888,3.640982

In [22]:
df_summary.describe()

,layer,samples,mean_base_margin,mean_new_margin,mean_margin_drop,t_stat,p_value,effect_size
count,64.000000,64.0,6.400000e+01,64.000000,64.000000,64.000000,6.400000e+01,64.000000
mean,15.500000,810.0,1.740147e+00,1.723472,0.016675,3.086516,6.823577e-02,0.108516
std,9.306083,0.0,2.237999e-16,0.067511,0.067511,8.659906,1.807084e-01,0.304466
min,0.000000,810.0,1.740147e+00,1.231659,-0.016800,-18.952232,4.856573e-90,-0.666325
25%,7.750000,810.0,1.740147e+00,1.733653,-0.000934,-1.477680,2.319341e-24,-0.051952
50%,15.500000,810.0,1.740147e+00,1.738450,0.001697,4.119735,2.668156e-12,0.144842
75%,23.250000,810.0,1.740147e+00,1.741081,0.006493,9.436354,2.593671e-03,0.331764
max,31.000000,810.0,1.740147e+00,1.756946,0.508488,22.929883,1.000000e+00,0.806172

In [27]:
x = [1,2,3,4,5,6,7]
k = 0
temp = x

In [ ]:

x[:-k] = temp[-k:]
x[-k:] = temp[:-k]
x

[5, 6, 7, 1, 2, 3, 4]

In [28]:
temp[:-k]

[]

In [32]:
[print(i) for i in range(1,5)]

1
2
3
4

[None, None, None, None]